### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ghost** [iru-/sam9f-unix#1]
To install this would one simply have to replace the sam and samterm folders of plan9port? Would I need to recompile?

**Comment by iru-** [comment]
To install, run `mk install` from the sam and samterm directories.
You don't have to replace anything beforehand. However, the sam9f-unix sam and samterm binaries will replace the plan9port ones in `$PLAN9/bin`.

Thanks for the question, I'll add a general mkfile and update the readme based on it as soon as possible.

**Comment by ghost** [comment]
Many thanks.

**Comment by ghost** [comment]
It would be helpful also if you could list changes/tweaks if any to the original version.

**Comment by iru-** [comment]
I try to only change the bare minimum needed to compile as other plan9port software, and run correctly. That usually means naming anonymous struct members and some dance with plan 9 affordances not present on unix. 
Regardless of the specific changes, they are always made on an ad-hoc basis for each synchronization with the 9front tree.

**Comment by ghost** [comment]
I see you have replaced the two folders you previously uploaded with the plan9front repo. I have now cloned this repo but would appreciate instructions on how to install it on Linux. If I run mk install in the sam and ssam directories as you previously indicated, nothing happens.

**Comment by iru-** [comment]
> I see you have replaced the two folders you previously uploaded with the plan9front repo.

I don't understand what you mean here.

> I have now cloned this repo but would appreciate instructions on how to install it on Linux. If I run mk install in the sam and ssam directories as you previously indicated, nothing happens.

Which repo did you clone?

From you comment it seems you have misunderstood what 9front is and what sam9f-unix is.

**Comment by ghost** [comment]
My apologies. I have been confused since I had my COVID shot! I was confusing your download links with the repo.
